### ISSUE TITLE
num-prepend and num-append properties dynamically

### ISSUE THREAD

**Issue by gglazer** [uhlryk/angular-dynamic-number#10]
Hi,
the "num-prepend" and "num-append" properties are very good things! :-)
How can I change num-prepend and num-append fields dynamically?
I've created a plunkr for this question: http://plnkr.co/edit/Fe93ksX6k6kbwPGvp70t?p=preview
Thanks in advance!

**Comment by uhlryk** [comment]
Hi,
I'm glad that you like it :)
For now we don't have functionality to dynamically change properties.
But this should be easy to create. And could be very helpful in many situations (not only for prepend and append)
I check it out in a few days.

**Comment by uhlryk** [comment]
I allow to dynamically change almost all of properties.
This changes are in v1.9.x
You can check then in this demo:
http://localhost:63342/angular-dynamic-number/examples/index.html#dynamic-properties
I also updated your plnkr. Unfortunately I made some changes also in script.js, because currency model watcher get stringified object. I don't know if there is some bug or something.
Here is link http://plnkr.co/edit/puGOJmC9p5ifwkPj48mz
maybe you improve it a little 
maybe it is good idea to add plunkers with some concepts to documentation?

**Comment by gglazer** [comment]
Hi,
I checked to your version and it works! Thanks!
I think plunkers are very good things for documentation...
