### ISSUE TITLE
Number reversed when typed on Android 4.2.2

### ISSUE THREAD

**Issue by mikmikmik** [uhlryk/angular-dynamic-number#12]
the cursor get stuck on the left so digits get inserted before, resulting in a reversed number.
(with the default browser, it works fine on firefox 46)

**Comment by uhlryk** [comment]
Hi 
thank you for your feedback.
Unfortunately this browser doesn't fully support js ecma script5 (all code is written with this). 
This directive need from browser cursor position to recalculate position after changes. 
It is in this method https://github.com/uhlryk/angular-dynamic-number/blob/master/src/numberDirective.js#L224
and I wrote it based on this:
http://stackoverflow.com/a/2897229/4138339
This is very important because in other case many features of this directive disappear. I think that android 4.2.2 doesn't return correct caret position. It could return always 0, whatever you write. 
I can't test it because I don't have all android phones and also it could be time consuming. And if I have right then I can't do nothing useful with this.
If this is problem with caret, only solution would be to create new version of this module which work without caret position. But that theoretical version would have less functionality.

If someone want to check this or even create android-dynamic-number for deprecated devices I will appreciate this.

**Comment by mikmikmik** [comment]
Thanks for your fast answer. 
I tried with https://github.com/es-shims/es5-shim without success.
Then I realized here https://github.com/uhlryk/angular-dynamic-number/blob/master/src/numberDirective.js#L233 it should be `oField.selectionEnd;` to match `oSel.text.length`.
Someone pointed out in the comment of your stackoverflow link it should be `iCaretPos = oField.selectionDirection=='backward' ? oField.selectionStart : oField.selectionEnd;`

I tried it on my files and it worked :)

**Comment by uhlryk** [comment]
super! 
if you create pull request I will add it to this repo.

**Comment by mikmikmik** [comment]
Done ;) Thanks for your work

**Comment by uhlryk** [comment]
Merged. Thank you too. 
I additionally increase version in bower.json and in package.json to publish it in npm and in bower.
