### ISSUE TITLE
does not work on input type="number"

### ISSUE THREAD

**Issue by miclill** [uhlryk/angular-dynamic-number#2]
"Error: [ngModel:numfmt] Expected `0` to be a number
http://errors.angularjs.org/1.4.8/ngModel/numfmt?p0=0
minErr/<@http://localhost:9000/bower_components/angular/angular.js:68:12
numberInputType/<@http://localhost:9000/bower_components/angular/angular.js:21977:1
ngModelWatch@http://localhost:9000/bower_components/angular/angular.js:25489:21
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9000/bower_components/angular/angular.js:15888:34
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9000/bower_components/angular/angular.js:16160:13
done@http://localhost:9000/bower_components/angular/angular.js:10589:36
completeRequest@http://localhost:9000/bower_components/angular/angular.js:10787:7
requestLoaded@http://localhost:9000/bower_components/angular/angular.js:10728:1

Workaround: input type="text"

**Comment by uhlryk** [comment]
Yes, this field must be text type. I wrote this in readme page in 'limitation section'.
This is because different browsers differently threat type number. For example  if your  browser  have as locals a comma, then this module can't override browser behavior.

Maybe this module could on init check if input has wrong type, and then in console write warning? What do you think?

**Comment by miclill** [comment]
Ah, sorry. I didn't catch this in the readme.
I think a warning would be nice.

**Comment by uhlryk** [comment]
I add warn if there is wrong input type, and bold type='text' in limitation section in readme.
