### ISSUE TITLE
awnum:price  is not working with filter on angular expressions

### ISSUE THREAD

**Issue by jsbimra** [uhlryk/angular-dynamic-number#26]
Hi,

I am trying to use custom strategy to format using filter option, but its not working.
Using following way 
`{{100000:awnum:price}}`
also tried with below:
`{{100000:awnum}}`

It working fine with input field not with angular expression. 

Any help appreciated.

Thanks.

**Comment by uhlryk** [comment]
Hi
Thank you for your feedback.
Please check how it works in examples:
https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html#L179
and there is working demo for examples. Above code is the last example here http://htmlpreview.github.io/?https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html
You should use it like this:
`{{model|awnum:price}}`  <- use `|` instead of `:` after model
Im not sure if you can use value as expression (for sure it works for models).

Please give me feedback if my comment help you.

**Comment by jsbimra** [comment]
Hi,

Sorry i was using pipe in my code like {{100000|awnum:price}} but while commenting here i made a mistake. 
But I found the gotcha, also was missing single quote around strategy name .
`{{100000|awnum: 'price'}}`
Now it worked. 

Thanks a lot for reference and pointing.

**Comment by uhlryk** [comment]
Thanks, 
I close this ticket.
